export const LOGIN_REQUEST="LOGIN.LOGIN_REQUEST";
export const LOGIN_SUCCESS="LOGIN.LOGIN_SUCCESS";
export const LOGIN_FAILURE="LOGIN.LOGIN_FAILURE";
export const LOGOUT="LOGOUT";

export const GET_HOLDER_GROUP_MASTER_LIST_SUCCESS="HolderGroupMaster.GET_HOLDER_GROUP_MASTER_LIST_SUCCESS"
export const GET_HOLDER_GROUP_MASTER_LIST_FAILURE="HolderGroupMaster.GET_HOLDER_GROUP_MASTER_LIST_FAILURE"

export const GET_ACCOUNT_HOLDER_MASTER_LIST_SUCCESS="AccountHolderMaster.GET_ACCOUNT_HOLDER_MASTER_LIST_SUCCESS"
export const GET_ACCOUNT_HOLDER_MASTER_LIST_FAILURE="AccountHolderMaster.GET_ACCOUNT_HOLDER_MASTER_LIST_FAILURE"

export const GET_STATUS_LIST_SUCCESS="HomePage.GET_STATUS_LIST_SUCCESS";


